using System;
using System.Collections.Generic;
using System.Text;

namespace WoerterLernen
{
    interface IListInitializer
    {
        List<LernElement> Read();
    }

    public class FromMemory : IListInitializer
    {
        public List<LernElement> Read()
        {
            var res = new List<LernElement>()
            {
                new LernElement("das Leben", "Жизнь", "[ˈleːbn̩]"),
                new LernElement("lesen","Читать", "[ˈleːzn̩]"),
                new LernElement("machen","делать", "[ˈmaχn̩]"),
                new LernElement("denken","думать","[ˈdɛŋkn̩]"),
                new LernElement("reisen","путешествовать","[ˈʁaɪ̯zn̩]"),
                new LernElement("spielen","играть","[ˈʃpiːlən]"),
                new LernElement("warten","ждать, дожидаться","[ˈvaʁtən]"),
                new LernElement("werden","становиться, делаться","[ˈveːɐ̯dn̩]"),
                new LernElement("wohnen","жить, обитать; проживать","[ˈvoːnən]"),
                new LernElement("das Alter","возраст","[ˈaltə]"),
                new LernElement("wollen","хотеть","[ˈvɔlən]"),
                new LernElement("die Eltern","родители","[ˈɛltɐ]"),
                new LernElement("die Familie, -en","семья","[faˈmiːli̯ə]"),
                new LernElement("die Frau, -en","женщина, жена","[fʁaʊ̯]"),
                new LernElement("das Kind, -er","ребенок","[kɪnt]"),
                new LernElement("das Jahr, -e","год","[jaːɐ̯]"),
                new LernElement("der Tag, -e","день","[taːk]"),
                new LernElement("der Monat, -e","месяц","[ˈmoːnat]"),
                new LernElement("ich","я","[ɪç]"),
                new LernElement("die Welt, -en","мир","[vɛlt]"),
                new LernElement("weiter","дальше","[ˈvaɪ̯tɐ]"),
                new LernElement("alles","всё","[ˈaləs]"),
                new LernElement("weit","далеко","[vaɪ̯t]"),
                new LernElement("bald","скоро","[balt]"),
                new LernElement("die Seite, -n","сторона; страница","[ˈzaɪ̯tə]"),
                new LernElement("durch","через, сквозь","[dʊʁç]"),
                new LernElement("die Zahl, -en","число","[ʦaːl]"),
                new LernElement("alt","старый; пожилой; древний; старинный","[alt]"),
                new LernElement("die Arbeit","труд, работа","[ˈaʁbaɪ̯t]"),
                new LernElement("frei","свободный, независимый","[fʁaɪ̯]"),
                new LernElement("immer","всегда","[ˈɪmɐ]"),
                new LernElement("klein","маленький, малый, небольшой","[klaɪ̯n]"),
                new LernElement("du","ты","[dʊ]"),
                new LernElement("neu","новый; недавний","[nɔɪ̯]"),
                new LernElement("verheiratet","женатый; замужняя","[fɛɐ̯ˈhaɪ̯ʁaːtət]"),
                new LernElement("verwitwet","овдовевший","[fɛɐ̯ˈvɪtvət]"),
                new LernElement("da","тут; там; здесь","[da]"),
                new LernElement("erst","сперва; только","[eːɐ̯st]"),
                new LernElement("etwa","около, приблизительно; разве","[ˈɛtva]"),
                new LernElement("etwas","нечто; что-нибудь; немного","[ˈɛtvas]"),
                new LernElement("hier","здесь, тут; вот","[ˈhɪɐ]"),
                new LernElement("jetzt","теперь, сейчас","[jɛʦt]"),
                new LernElement("leider","к сожалению","[ˈlaɪ̯dɐ]"),
                new LernElement("noch","(пока), ещё; по-прежнему; всё ещё","[nɔχ]"),
                new LernElement("kein","никакой","[kaɪ̯n]"),
                new LernElement("schon","уже","[ʃoːn]"),
                new LernElement("übrigens","впрочем, вообще","[ˈyːbʁɪɡn̩s]"),
                new LernElement("aber","но","[ˈaːbɐ]"),
                new LernElement("aus","из","[aʊ̯s]"),
                new LernElement("das (es),","это","[das]"),
                new LernElement("dein","твой (твоя, твоё, твои),","[daɪ̯n]"),
                new LernElement("von","от","[fɔn]"),
                new LernElement("was","что?","[vas]"),
                new LernElement("wer","кто?","[veːɐ̯]"),
                new LernElement("wie","как?","[viː]"),
                new LernElement("wieviel","сколько?","[viːˈfiːl]"),
                new LernElement("ach so!","вот как!, значит так!, ах так!","[ax zɔ]"),
                new LernElement("auf Wiedersehen!","до свидания!","[aʊ̯f ˈviːdɐˌzeːən]"),
                new LernElement("schön","красивый, прекрасный","[ʃøːn]"),
                new LernElement("stehen","стоять","[ˈʃteːən]"),
                new LernElement("der Abend, -e","вечер","[ˈaːbn̩t]"),
                new LernElement("zur Zeit","в настоящее время","[tsuːɐ̯ ʦaɪ̯t]"),
                new LernElement("der Mann, die Männer","мужчина, супруг","[man]"),
                new LernElement("fest","крепкий, прочный, твердый","[fɛst]"),
                new LernElement("nicht","не, ни","[nɪçt]"),
                new LernElement("der Lehrer","учитель; преподаватель; наставник","[ˈleːʁɐ]"),
                new LernElement("und","и","[ʊnt]"),
                new LernElement("das Land, die Länder","страна; край","[lant]"),
                new LernElement("auch","также, тоже; и; впрочем","[aʊ̯χ]"),
                new LernElement("später","поздний; позднеe; после этого","[ˈʃpɛːtɐ]"),
                new LernElement("dort","там","[dɔʁt]"),
                new LernElement("kaufen","купить; покупать","[ˈkaʊ̯fn̩]"),
                new LernElement("verkaufen","продавать","[fɛɐ̯ˈkaʊ̯fn̩]"),
                new LernElement("zusammen","вместе; сообща","[ʦuˈzamən]"),
                new LernElement("dann","тогда; потом, затем","[dan]"),
                new LernElement("die Stunde, -n","час","[ˈʃtʊndə]"),
                new LernElement("möglich","возможный (возможно),","[ˈmøːklɪç]"),
                new LernElement("die Liebe","любовь","[ˈliːbə]"),
                new LernElement("liegen","лежать; быть расположенным","[ˈliːɡn̩]"),
                new LernElement("antworten","отвечать; давать ответ","[ˈantˌvɔʁtn̩]"),
                new LernElement("kommen","приходить, прибывать","[ˈkɔmən]"),
                new LernElement("entschuldigen","извинять, прощать","[ɛntˈʃʊldɪɡn̩]"),
                new LernElement("funktionieren","функционировать; действовать; работать","[fʊŋkʦi̯oˈniːʁən]"),
                new LernElement("kosten","стоить; пробовать","[ˈkɔstn̩]"),
                new LernElement("sagen","сказать; говорить","[ˈzaːɡn̩]"),
                new LernElement("spülen","полоскать, промывать, мыть"," [ˈʃpyːlən]"),
                new LernElement("stimmen","соответствовать (истине),; быть верным","[ˈʃtɪmən]"),
                new LernElement("waschen","мыть; стирать; промывать","[ˈvaʃn̩]"),
                new LernElement("wechseln","менять(ся); обменивать; разменивать","[ˈvɛksl̩n]"),
                new LernElement("die Antwort, -en","ответ; отклик","[ˈantˌvɔʁt]"),
                new LernElement("das Benzin,","бензин","[bɛnˈʦiːn]"),
                new LernElement("das Bett, -en","постель; кровать","[bɛt]"),
                new LernElement("das Bild, -er","картина; рисунок","[bɪlt]"),
                new LernElement("der Fehler","ошибка","[ˈfeːlɐ]"),
                new LernElement("heißen","называть, зваться","[ˈhaɪ̯sn̩]"),
                new LernElement("das Geld","деньги","[ɡɛlt]"),
                new LernElement("das Geschäft, -e","дело, занятие; сделка; магазин","[ɡəˈʃɛft]"),
                new LernElement("das Haus, die Häuser","дом, здание, строение","[haʊ̯s]"),
                new LernElement("der Haushalt, -e","домашнее хозяйство","[ˈhaʊ̯shalt]"),
                new LernElement("der Herd, -e","очаг, плита","[heːɐ̯t]"),
                new LernElement("die Idee, -n","идея; мысль; замысел; намерение","[iˈdeː]"),
                new LernElement("können","мочь, уметь","[ˈkœnən]"),
                new LernElement("schnell","быстро","[ʃnɛl]"),
                new LernElement("sein","быть","[zaɪ̯n]"),
                new LernElement("das Regal, -e","полка; стеллаж","[ʁeˈɡaːl]"),
                new LernElement("anders","по другому","[ˈandɐs]"),
                new LernElement("in","в, внутри","[ɪn]"),
                new LernElement("haben","иметь","[ˈhaːbn̩]"),
                new LernElement("der Stuhl, die Stühle","стул","[ʃtuːl]"),
                new LernElement("der Tisch, -e","стол","[tɪʃ]"),
                new LernElement("der Topf, die Töpfe","горшок; кастрюля","[tɔpf]"),
                new LernElement("die Uhr, -en","часы","[uːɐ̯]"),
                new LernElement("die Sonne","солнце","[ˈzɔnə]"),
                new LernElement("gehen","идти, ходить; уходить","[ˈɡeːən]"),
                new LernElement("die Zeit","время","[ʦaɪ̯t]"),
                new LernElement("ähnlich","похожий; сходный; подобный","[ˈɛːnlɪç]"),
                new LernElement("sehen","смотреть, глядеть","[ˈzeːən]"),
                new LernElement("ehrlich","честный; порядочный","[ˈeːɐ̯lɪç]"),
                new LernElement("kaputt","разбитый; сломанный; разорванный; погибший","[kaˈpʊt]"),
                new LernElement("groß","большой, крупный","[ɡʁoːs]"),
                new LernElement("lustig","весёлый; радостный; забавный, смешной","[ˈlʊstɪç]"),
                new LernElement("originell","оригинальный, своеобразный; странный","[oʁiɡiˈnɛl]"),
                new LernElement("sehr","очень, весьма; крайне","[zeːɐ̯]"),
                new LernElement("heute","сегодня","[ˈhɔɪ̯tə]"),
                new LernElement("viel","много; многие; многое","[fiːl]"),
                new LernElement("oder","или","[ˈoːdɐ]"),
                new LernElement("sondern","а, но","[ˈzɔndɐn]"),
                new LernElement("zu","к, на; в","[ʦuː]"),
                new LernElement("raus","наружу","[ʁaʊ̯s]"),
                new LernElement("danke","спасибо","[ˈdaŋkə]"),
                new LernElement("bitte","пожалуйста","[ˈbɪtə]"),
                new LernElement("die Lampe, -n","лампа","[ˈlampə]"),
                new LernElement("trinken","пить","[ˈtʁɪŋkn̩]"),
                new LernElement("essen","есть, кушать","[ˈɛsn̩]"),
                new LernElement("der Bleistift, -e","карандаш","[ˈblaɪ̯ˌʃtɪft]"),
                new LernElement("ordnen","приводить в порядок; систематизировать","[ˈɔʁdnən]"),
                new LernElement("der Beruf, -e","профессия; специальность","[bəˈʁuːf]"),
                new LernElement("der Arzt, die Ärzte","врач; доктор","[aːɐ̯ʦt]"),
                new LernElement("der Baum, die Bäume","дерево","[baʊ̯m]"),
                new LernElement("nach","после","[naːχ]"),
                new LernElement("auf","на (горизонтальной пов-ти)","[aʊ̯f]"),
                new LernElement("gegen","против; около","[ˈɡeːɡn̩]"),
                new LernElement("als","как, когда","[als]"),
                new LernElement("das Auto, -s","автомобиль","[ˈaʊ̯to]"),
                new LernElement("er","он","[ɐ]"),
                new LernElement("bestellen","заказывать","[bəˈʃtɛlən]"),
                new LernElement("bezahlen","платить; выплачивать; расплачиваться","[bəˈʦaːlən]"),
                new LernElement("brauchen","нуждаться","[ˈbʁaʊ̯χn̩]"),
                new LernElement("genau","точно, именно","[ɡəˈnaʊ̯]"),
                new LernElement("glauben","полагать, думать; верить","[ˈɡlaʊ̯bn̩]"),
                new LernElement("kochen","варить, готовить (пищу); стряпать; кипятить","[ˈkɔχn̩]"),
                new LernElement("mögen","любить; чувствовать расположение ","[ˈmøːɡən]"),
                new LernElement("über","над","[ˈyːbɐ]"),
                new LernElement("üben","упражняться","[ˈyːbn̩]"),
                new LernElement("das Abendessen","ужин","[ˈabn̩tˌʔɛsn̩]"),
                new LernElement("die Anzeige, -n","объявление; заявление, уведомление","[ˈanˌʦaɪ̯ɡə]"),
                new LernElement("der Apfel, die Äpfel","яблоко","[ˈapfl̩]"),
                new LernElement("müssen","быть должным","[ˈmʏsn̩]"),
                new LernElement("das Brot, -e","хлеб","[bʁoːt]"),
                new LernElement("zwischen","между","[ˈʦvɪʃn̩]"),
                new LernElement("die Butter","масло (животное)","[ˈbʊtɐ]"),
                new LernElement("unter","под","[ˈʊntɐ]"),
                new LernElement("das Ei, die Eier","яйцо","[aɪ̯]"),
                new LernElement("das Eis","лёд; мороженое","[aɪ̯s]"),
                new LernElement("die Erdbeere, -n","клубника, земляника","[ˈeːɐ̯tbeːʁə]"),
                new LernElement("die Flasche, -n","бутылка; фляжка","[ˈflaʃə]"),
                new LernElement("das Fleisch","мясо","[flaɪ̯ʃ]"),
                new LernElement("die Frage, -n","вопрос","[ˈfʁaːɡə]"),
                new LernElement("selbst","сам","[zɛlpst]"),
                new LernElement("das Frühstück, -e","завтрак","[ˈfʁyːˌʃtʏk]"),
                new LernElement("die Gabel, -n","вилка","[ˈɡaːbl̩]"),
                new LernElement("die Zeitung, -en","газета","[ˈʦaɪ̯tʊŋ]"),
                new LernElement("das Gemüse","овощи, зелень","[ɡəˈmyːzə]"),
                new LernElement("das Gericht, -e","блюдо, кушанье; суд","[ɡəˈʁɪçt]"),
                new LernElement("das Gespräch, -e","разговор; беседа","[ɡəˈʃpʁɛːç]"),
                new LernElement("das Getränk, -e","напиток; питьё","[ɡəˈtʁɛŋk]"),
                new LernElement("das Gewürz, -e","пряности; приправа","[ɡəˈvʏʁʦ]"),
                new LernElement("das Glas, die Gläser","стекло; стакан; рюмка","[ɡlaːs]"),
                new LernElement("das Prozent, -e","процент","[pʁoˈʦɛnt]"),
                new LernElement("der Käse","сыр; творог","[ˈkɛːzə]"),
                new LernElement("der Kuchen,","- пирог; пирожное","[ˈkuːχn̩]"),
                new LernElement("der Löffel, =","ложка","[ˈlœfl̩]"),
                new LernElement("mehr","больше","[meːɐ̯]"),
                new LernElement("das Messer, =","нож","[ˈmɛsɐ]"),
                new LernElement("der Nachtisch, -e","десерт","[ˈnaːχˌtɪʃ]"),
                new LernElement("das Öl, -e","масло (растительное)","[øːl]"),
                new LernElement("der Pfeffer","перец","[ˈpfɛfɐ]"),
                new LernElement("die Blume","цветок","[ˈbluːmə]"),
                new LernElement("der Preis, -e","цена","[pʁaɪ̯s]"),
                new LernElement("der Reis","рис","[ʁaɪ̯s]"),
                new LernElement("der Saft, die Säfte","сок","[zaft]"),
                new LernElement("die Sahne","сливки","[ˈzaːnə]"),
                new LernElement("der Schinken,","ветчина","[ˈʃɪŋkn̩]"),
                new LernElement("die Soße, -n","соус, подливка","[ˈzoːsə]"),
                new LernElement("langsam","медленно","[ˈlaŋˌzaːm]"),
                new LernElement("das Wasser","вода","[ˈvasɐ]"),
                new LernElement("die Suppe, -n","суп; похлёбка","[ˈzʊpə]"),
                new LernElement("die Tasse, -n","чашка (чайная)","[ˈtasə]"),
                new LernElement("der Teller","тарелка","[ˈtɛlɐ]"),
                new LernElement("die Tomate, -n","помидор","[toˈmaːtə]")
            };
            return res;
        }
    }
}
